services:
  - type: web
    name: pal-hotel-api
    env: java
    plan: free
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/sweet-shop-backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pal-hotel-db
          property: internalUrl
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pal-hotel-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pal-hotel-db
          property: password